spring.application.name=bank-rest-app

## Server Configuration
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
#spring.flyway.enabled=${SPRING_FLYWAY_ENABLED}
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=${SPRING_JPA_HIBERNATE_DIALECT}
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=true
#jwt.secret=${SPRING_JWT_SECRET}
#jwt.lifetime=${SPRING_JWT_LIFETIME}

resend.api.key=re_YgZFi2ES_NWRZSo3X5b4pDkxZGHhkwKrc

spring.datasource.url=jdbc:postgresql://localhost:5432/bank
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
jwt.secret=+tZCYoFX3/GOatpDsu++paJ0wtJOm/2wIfXrwjXzGNM=
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
jwt.lifetime=3600000
server.address=0.0.0.0
logging.level.root=INFO
# Включаем детальный лог Spring Security (покажет, на каком фильтре падает 403)
logging.level.org.springframework.security=DEBUG
# Логируем SQL запросы и параметры, которые в них подставляются
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Твой пакет приложения (замени, если путь отличается)
logging.level.bank.rest.app=DEBUG

# Общий уровень для веба
logging.level.org.springframework.web=DEBUG
#spring.jpa.hibernate.ddl-auto=update

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=emulationbank@gmail.com
spring.mail.password=ihnx qcjt kcol htns
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.aop.proxy-target-class=true