CREATE TABLE IF NOT EXISTS payments (
    payment_id BIGINT PRIMARY KEY DEFAULT nextval('payment_seq'),
    payment_type VARCHAR(50) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    payment_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL,
    currency_code VARCHAR(10),
    purpose VARCHAR(255),
    account_id INTEGER,
    recipient_name VARCHAR(255),
    recipient_iban VARCHAR(34),
    tax_number VARCHAR(50),
    provider_name VARCHAR(255),
    contract_number VARCHAR(100),
    operator_name VARCHAR(255),
    phone_number VARCHAR(32),
    service_provider VARCHAR(255),
    client_address VARCHAR(255),
    utility_account_number VARCHAR(100),
    CONSTRAINT fk_payments_account FOREIGN KEY (account_id) REFERENCES account (account_id)
);
