ALTER TABLE payment
    ADD COLUMN IF NOT EXISTS payment_type VARCHAR(20) DEFAULT 'IBAN' NOT NULL,
    ADD COLUMN IF NOT EXISTS tax_number VARCHAR(20),
    ADD COLUMN IF NOT EXISTS client_address VARCHAR(255),
    ADD COLUMN IF NOT EXISTS status VARCHAR(20),
    ADD COLUMN IF NOT EXISTS currency_code VARCHAR(10),
    ADD COLUMN IF NOT EXISTS recipient_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS recipient_iban VARCHAR(34),
    ADD COLUMN IF NOT EXISTS provider_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS contract_number VARCHAR(100),
    ADD COLUMN IF NOT EXISTS operator_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS phone_number VARCHAR(32),
    ADD COLUMN IF NOT EXISTS service_provider VARCHAR(255),
    ADD COLUMN IF NOT EXISTS utility_account_number VARCHAR(100);
